const enTranslation = {
    //Header
    "for students": "For students",
    "for companies": "For companies",
    "about": "About us",

    //Footer
    "contact": "Contact",

    //Home page 
    "welcome": "Welcome to",
    "f-s": "the F-guilds",
    "career fair": "career fair",
    "dates": "30 January 2025",
    "quick desc": "Farad is the F-guild at LTH's career fair, where companies get the opportunity to get in touch with students from the programs Engineering Physics, Engineering Mathematics and Engineering Nanoscience.",
    "signup": "Register your company by contacting",
    "to companies": "Are you interested in participating in FARAD 2025? We offer packages to suit all budgets and levels of ambition. Learn more under 'For Companies'!",
    "prios": "Our priority partners",
    "what": "What is FARAD?",
    "home1": "Welcome to FARAD - the career fair of the F-section. FARAD exists to serve as an information hub between the job market and students, offering you an opportunity to enhance your employer brand among our future engineers and to inform them about why your company is an attractive employer.",
    "home2": "The F-section is one of the largest sections at LTH and consists of the programs Engineering Physics, Engineering Mathematics, and Engineering Nanoscience. Our students are highly skilled and at the forefront in many fields of study, including modeling and programming, which we are very proud of!",
    "home3": "FARAD offers you a unique opportunity to network with Sweden's most promising engineering students and showcase your company's vision and career opportunities. Secure your spot now!",
    "what happens": "What happens during FARAD?",
    "lightbringer lunch": "Lunch lecture with Lightbringer",
    "svl lunch": "Lunch lecture with SVL",
    "january": "January",
    "fairday": "Day of the fair!",
    "foajen": "The foyer of the mathematics building",
    "if lunch": "Lunch lecture with If",
    "banquett": "Banquet",
    "gasque": "The banquet hall in the union house",

    //Company page
    "companies": "Företag",
    "company doc": "In this document you as a company may find all of the different price plans that we offer you to choose from",
    "company invite": "Would you like to participate in FARAD?",
    "packages": "Our packages",
    "base package": "Base package",
    "6m": "6m^2 booth space",
    "adds": "Advertising in the section's media",
    "2 banquet": "2 tickets to the FARAD banquet",
    "2 lounge": "2 tickets to the business lounge with breakfast, lunch, and coffee",
    "helper": "A company host to assist you with everything you can imagine!",
    "prio package": "Priority package",
    "prio placement": "Priority placement at the fair",
    "more adds": "Extended advertising in the section's media",
    "6 lounge": "6 tickets to the business lounge with breakfast, lunch, and coffee",
    "main sponsor": "Main sponsor",
    "9m": "9m^2 booth space",
    "even more adds": "Significantly extended advertising in the section's media",
    "website logo": "Your logo on the website",
    "lunch lecture": "Lunch lecture",
    "4 banquet": "4 tickets to the FARAD banquet",
    "more options": "Additional offers",
    "more space": "Extended fair space",
    "9m extra": "9m^2 additional booth space",
    "lunch info": "A lecture from 12:15 to 13:00 for approximately 150 students, where your company gets the chance to capture the interest of students in years 4-5 and introduce yourselves to students in years 1-3. We can confidently guarantee at least 70-100 students will attend.",
    "contact talks": "Contact meetings",
    "contact talks pricing": "5000 SEK for 5 students + 1000 kr/additional student",
    "contact talks info": "Your company provides a requirement profile for the students you wish to meet. The project team will deliver 5 students matching the profile and provide you with a quiet room for the meetings.",

    //Students page
    "students": "Students",
    "work": "Do you want to work at FARAD? Of course you do! Then sign up at this link:",
    "moreinfo": "More info coming soon",

    //About page
    "weare": "We are the project group!",
    "weare_extended": "We are the project group of FARAD 2025! We have marketed the fair, planned events, fixed the logistics, built a webpage, written the Alumni Calendar, scouted for hosts and invited all of the companies! We want to say a big thanks for this year to all of the companies and institutions who attended the fair and to all of our wonderful hosts that enabled the fair!",

    //Exhibitors
    "exhibitors": "Exhibitors",
    "ericsson_desc": "At Ericsson you’ll have a unique opportunity. The chance to use your skills and imagination to push the boundaries of what’s possible. To create never-seen-before solutions to some of the world’s toughest problems. You’ll be challenged. But you won’t be alone. You’ll be part of a team of like-minded innovators, all driven to go beyond the status quo to build what comes next. You’ll collaborate across disciplines, borders and continents. You’ll be empowered to lead and perform at your best. You’ll shape technology for people, societies, industries and humanity. You’ll be part of a diverse community where you can bring your own perfectly-unique self to work. At Ericsson you can be an explorer, a change maker and a force for good. Imagine a better, brighter tomorrow. You can be the one who makes it possible.",
    "lightbringer_desc": "Lightbringer is one of Sweden’s hottest AI startups, revolutionizing the way companies innovate and protect their ideas. We combine cutting-edge technology with a deep understanding of the patent landscape to empower creators, engineers, and businesses worldwide. Our world-class team in Lund is growing, and we’re on the lookout for exceptional individuals who share our passion for reshaping the future of innovation. Whether you’re seeking a hands-on summer internship, a master’s thesis project that tackles real-world challenges, or a full-time position with global impact, Lightbringer has a place for you. Join us today and help shape tomorrow’s world, and far beyond.",
    "if_desc": "Are you interested in statistics and data analysis and want to use it in business decisions? Kickstart your career with us at If! As the largest insurance company in the Nordic region, we regularly analyze large amounts of data and trends to keep our pricing up to date. Another important job we do is using our data to detect potential fraud. We’re looking for new analysts who enjoy coding in Python and diving into data while making a difference in society and people’s lives. If that sounds exciting, feel free to stop by and chat with us at FARAD! \n\n Are you in your 3rd or 4th year? Check out our summer job as an analyst, and if you’re interested, there may also be opportunities for a thesis project. If you’re at the end of your studies, make sure to apply for our analyst trainee program :smiley: \n\n Link to the trainee program: https://if.wd3.myworkdayjobs.com/en-US/Careers/details/If-Trainee-Program-2025_JobReqID8835-1",
    "axis_desc": "Axis Communications is a Swedish company specializing in network solutions, particularly in video surveillance. Founded in 1984, Axis pioneered the development of the world’s first network camera in 1996, revolutionizing the security industry. We focus on innovative, high-quality products that combine advanced technology with sustainability, enabling businesses and public organizations to enhance safety and operational efficiency. \n\n We offer a broad portfolio of network cameras, video encoders, audio systems, and analytics software, catering to diverse industries such as retail, healthcare, transportation, and critical infrastructure. \n\n Headquartered in Lund, Sweden, we operate globally with a strong commitment to local partnerships and environmental responsibility. As a market leader, Axis continues to shape the future of smart security solutions, driving innovation. \n\n During our 40-year-old journey, we have worked closely with students, and we are excited to continue to do so. If you want to learn more about how it is to be a student at Axis. Come speak to us at FARAD and read more at: https://www.axis.com/careers/student-opportunities.",
    "dfine_desc": "We at d-fine are over 1500 colleagues with backgrounds mainly in mathematics and physics. By combining our quantitative background, IT expertise and a strong understanding of our clients’ business, we support our customers in solving their challenges using analytics as well as in developing future-proof technological solutions. d-fine has offices in seven European countries, including our office in Stockholm since early 2023 and we support companies in all major industries across Europe. \n\n We are looking for students and soon-to-be graduates on the Master or PhD level in highly quantitative fields with dedication to the quality of their work. Meet us at our booth to learn more about the opportunities we offer you as a consultant with us – challenging projects, positive company culture, continuous education programs (e.g. MBA), regular conferences, and much more. At d-fine, it's not about elbows, it's about excellent results, teamwork, and genuine knowledge. We are looking forward to meeting you!",
    "sveing_desc": "Start your life as an engineer with us. \n\n Sveriges Ingenjörer is a union for those studying to become or working as engineers. We support you already during your studies and prepare you for your future career as an engineer. \n\n For only 15 SEK/month, you get advantageous insurance, access to scholarships, an unbeatable network, and advice. You also gain access to Ny Teknik's digital premium service, where you can read about the latest in innovation, technology, and entrepreneurship. \n\n While you focus on your studies, we focus on you. Become a member today: https://www.sverigesingenjorer.se/medlemskap/",    "iaeste_desc": "IAESTE erbjuder kvalificerad och betald praktik i runt 80 länder – i första hand för teknologer, naturvetare och arkitekter, men även för exempelvis ekonomer. Våra praktikutbyten ger dig möjligheter till nya värdefulla erfarenheter, minnen för livet och kommer att stärka ditt CV!",
    "algorithma_desc": "Hi! We are Algorithma, a consulting firm specializing in tech, AI, and strategy. We help companies grow and create value by combining innovation, strategy, and cutting-edge technology. At Algorithma, you’ll find a mix of strategy experts, AI specialists, and transformation leaders – all driven by the goal of shaping the future of the tech landscape. \n\n We’re looking for passionate data scientists who love technology and AI. Do you want to tackle exciting challenges, develop future-proof solutions, and make an impact in a fast-changing world? Then Algorithma is the right place for you! We have offices in Stockholm and Gothenburg. \n\n Come and talk to us to learn more about what we do and how we can grow together! ",
    "nanolund_desc": "NanoLund: The place to do Nanoscience and prepare for a career in academia or industry \n\n NanoLund is Sweden’s largest research environment for interdisciplinary Nanoscience and nanotechnology. We are an international, highly visible nanoscience center that offers exceptional scientific opportunities, training, and career development. We do this through a strong culture of openness and by offering access to an incredibly wide range of capabilities within characterization, fabrication and modelling. \n\n NanoLund is built on a high degree of collaboration between research groups that span multiple disciplines. NanoLund will remain at the forefront of pioneering new research directions and contributing to high-quality Nanoscience and Nanotechnology at the international level. As a center NanoLund aspires to be an open and creative environment that encourages collaboration, mutual inspiration and support, the sharing of knowledge, and an open attitude and that offers ideal opportunities for education and career development. \n\n The 130 PhD students form 1/3 of NanoLund and are employed in engineering, natural sciences, and medicine. As a PhD student you will be embedded in an active research topic and trained in state-of-the-art technology and methods. As a PhD you will receive training in general research as well as leadership skills, get an introduction to our wide range of networks, and gain access to our mentorship program. After the PhD you continue in science or change to industry using the networks to find otherwise closed positions. A PhD with us opens many doors is much more than “just” another degree, it is the start of a career.",
    "llc_desc": "Lund Laser Centre (LLC, www.llc.lu.se) is an organization for interdisciplinary research in optics, spectroscopy, and lasers at Lund University. At LLC, there are over 300 laser systems spread across more than 30 research laboratories, used by about 200 researchers from the Faculties of Engineering, Science, and Medicine. Nearly half of these are PhD students and thesis workers, and LLC's departments offer great opportunities for those interested in doing their thesis work or pursuing a PhD in both basic and applied research utilizing modern laser technology.",
    "svl_desc": "LTH's Study and Career Guidance offers individual career counseling, coaching, and lectures. If you are nearing the end of your education, you are offered career coaching in the form of a self-guided course – Your Next Step – on Canvas. After completing the course, you should be able to define who you are, what you want to do, and where you want to do it, envision your dreams, see future opportunities, take chances, and plan ahead. \n\n We are proud to collaborate with the FARAD project group and invite you to a lecture on the topic: \"How can you best prepare for the fair.\"",
    "regler_desc": "The Department of Automatic Control was founded in 1965 by Karl Johan Åström and currently has about 55 employees. We offer undergraduate and advanced courses for almost all programs at LTH, but our main activity is research in large-scale systems and machine learning, autonomous real-time systems, and innovative control applications. Each year, we recruit about 4–5 new PhD students, most of whom have studied the F or Pi programs at LTH. We also offer skilled engineering students the opportunity to work as lab or exercise leaders.",
    "sentianai_desc": "We specialize in delivering leading-edge Industrial AI solutions specifically tailored for the mining industry, representing a new era of process optimization. Our approach is marked by remarkable advancements in performance, sustainability, and efficiency. \n\n At our core, we leverage state-of-the-art AI to address the intricate challenges of process optimization within mining operations. Our expertise shines in managing complex, nonlinear interactions among numerous variables and trade-offs inherent to mining processes. \n\n Empowering mining operations is our primary focus , providing guidance and AI-assisted decision-making. \n\n Excitingly, we have recently become a part of The Weir Group PLC, a global leader in mining technology. This strategic acquisition aligns with our commitment to helping mining industries operate with the highest productivity and lowest environmental impact. \n\n Our Socials \n\n Website: https://sentian.ai \n\n LinkedIn: https://www.linkedin.com/company/15157579/admin/feed/posts/",
    "netcompany_desc": "Netcompany is a pure-play IT services company, delivering critical IT projects to both the private and public sector. By building agile, scalable, and secure digital solutions, Netcompany is positioned to drive Europe towards a sustainable future in a decade of digitalisation. Netcompany was founded in 2000 with headquarters in Copenhagen, Denmark. Today, we are an international company with more than 7700 employees from over 50 different nationalities, working from more than 10 countries. \n\n At Netcompany, we’re dedicated to creating innovative IT solutions that make a real difference. As part of our Operations department, you’ll play a key role in ensuring that businesses, public institutions and citizens can rely on seamless and secure digital services. From optimizing IT infrastructure to managing complex systems, you’ll help shape the backbone of tomorrow’s digital society. \n\n Joining Netcompany means becoming part of a team that values collaboration, continuous development and making a lasting impact. You’ll work in a dynamic environment where your ideas and skills are valued, and you’ll have the opportunity to grow professionally while solving exciting challenges. \n\n Come meet us at FARAD on January 30th, 2025 and let’s explore how you can kickstart your career with us.",
    "linc_desc": "LINC-STEM’s role within the finance society LINC is to provide all our members, especially those within Science, Technology, Engineering and Mathematics the knowledge to take the step into finance. With the ever-progressing world of technology, students with these key technical skills are heavily sought after and this committee will provide you with both the tools and the network to establish a connection with a suitable employer. \n\n Throughout the year our committee organizes a wide variety of events such as the annual Hackathon: “A Day in the Life of a Trader”, the Copenhagen Finance Tour, Python workshops, and more. Additionally, LINC-STEM plays a significant role in the Trading & Quantitative Research (TQR) teams of R&A, which recruit students at the start of each academic year. All of our events have the common goal of preparing our members with the valuable skill set that is vital when pursuing a career within finance.",
}
  
export default enTranslation;
